baseurl = "http://example.com/"
theme = "hugo-geo"	
relativeURLs = false
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "dacherreragu@unal.edu.co"

	profilepic = "img/David.jpg"
	
	title = "David Herrera Gutiérrez"
	subtitle = "GitHub Page"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/dacherreragu"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/HerreraDavid95"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com/in/david-herrera-gutiérrez-2b44868a"
	[[params.socialbuttons]]
	faicon = "google-plus"
	url = "https://plus.google.com/u/0/102807352685138209097"
	[[params.navlinks]]
	name = "About"
	url = "file:///home/david/Workdir/dacherreragu.github.io/about.html"
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"
